# Generated by Django 4.1.4 on 2023-02-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_data_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
